Repository CodeForAfrica/Data4SDGs-AQ-Map, pull requests merged in 2021-02, with the labels that each got.

#11 Filter Nodes by Network
  src/css/style.css
  src/index.html
  src/js/index.js
Labels: enhancement

#12 [Fix] Add Sensor.Community to Table
  src/js/index.js
Labels: bug

#13 Udpate docs
  README.md
Labels: documentation

#14 Update README.md
  README.md
Labels: documentation

#15 Update CNAME
  src/CNAME
Labels: enhancement

#16 Get nodes from Dashboard
  src/js/feinstaub-api.js
  src/js/index.js
Labels: enhancement
